version: '1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: pairupbackend.settings
      POSTGRES_DB: pairup
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: pairup
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
